name: main
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install black==22.10.0

      - run: black --check .

  flak8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install flake8

      - run: flake8 --max-line-length 88

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install isort

      - run: isort . --check --profile black --filter-files

  pytest:
    needs: [black, flake8, isort]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install pytest

      - run: pytest