name: main
on: [push, pull_request]
jobs:
  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv '

      - run: |
          python -m pip install --upgrade pip
          pip install black

      - run: black --check .